apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: {{ .Values.nodeClass.name }}
spec:
  amiFamily: {{ .Values.nodeClass.amiFamily }}
  role: {{ .Values.nodeIamRoleName }}
  amiSelectorTerms:
    - alias: {{ .Values.nodeClass.amiAlias }}

  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: {{ .Values.clusterName }}

  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: {{ .Values.clusterName }}

  tags:
    Name: {{ .Values.clusterName }}-karpenter-node
