apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: default
  namespace: karpenter
spec:
  amiFamily: AL2
  role: "KarpenterNodeRole"
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: "true"
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: "true"
  tags:
    ManagedBy: "karpenter"
    Environment: "production"
  userData: |
    #!/bin/bash
    echo "Karpenter managed node launched"
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        volumeSize: 32Gi
        volumeType: gp3
        deleteOnTermination: true
