apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: default
  namespace: karpenter
spec:
  template:
    metadata:
      labels:
        workload-type: general
    spec:
      requirements:
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["on-demand"]
        - key: kubernetes.io/arch
          operator: In
          values: ["arm64"]
        - key: node.kubernetes.io/instance-type
          operator: In
          values: ["t4g.medium"]
        - key: karpenter.sh/do-not-evict
          operator: In
          values: ["false"]
      nodeClassRef:
        name: default
      taints:
        - key: workload-type
          value: general
          effect: NoSchedule
  limits:
    cpu: 1000
    memory: 1000Gi
  disruption:
    consolidateAfter: 30s
    consolidationPolicy: cost
    expireAfter: 604800s
    budgets:
      - nodes: "10%"
  weight: 100
