apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: graviton
spec:
  template:
    spec:
      nodeClassRef:
        name: dev-creato

      requirements:
        - key: "kubernetes.io/arch"
          operator: In
          values: ["arm64"]

        - key: "node.kubernetes.io/instance-type"
          operator: In
          values:
            - "t4g.medium"
            - "t4g.large"
            - "m6g.large"
            - "c6g.large"

        - key: "karpenter.k8s.aws/instance-generation"
          operator: Gt
          values: ["4"]

        - key: "karpenter.k8s.aws/capacity-type"
          operator: In
          values: ["on-demand", "spot"]

  limits:
    cpu: 100

  disruption:
    consolidationPolicy: WhenUnderutilized
    consolidateAfter: 2m
    expireAfter: 720h
